site_name: Smart Steps AI
site_description: Documentation for the Smart Steps AI Professional Persona module
site_author: Smart Steps Team
repo_url: https://github.com/deftech/smart-steps-ai
repo_name: deftech/smart-steps-ai

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference:
    - Overview: api/index.md
    - Cache Manager: api/cache_manager.md
    - Memory Optimizer: api/memory_optimizer.md
    - Knowledge Store: api/knowledge_store.md
    - Layered Memory: api/layered_memory.md
    - Session Manager: api/session_manager.md
    - Persona Manager: api/persona_manager.md
  - CLI Reference:
    - Overview: cli/index.md
    - Performance Commands: cli/performance.md
    - Session Commands: cli/session.md
    - Conversation Commands: cli/conversation.md
    - Analysis Commands: cli/analysis.md
    - Config Commands: cli/config.md
    - Persona Commands: cli/persona.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Performance Optimization: tutorials/performance_optimization.md
  - Performance Optimization: performance.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - footnotes
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [smart_steps_ai]
          options:
            docstring_style: google
            show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deftech/smart-steps-ai
  version:
    provider: mike
